# Generated by Django 5.2.16 on 2026-07-26 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор опроса",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistic",
                to="main.survey",
                verbose_name="Опросник",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="main.survey",
                verbose_name="Опрос",
            ),
        ),
    ]
